### ISSUE TITLE
启动后终端直接卡死

### ISSUE THREAD

**Issue by clover-cn** [Ackites/KillWxapkg#10]
![image](https://github.com/user-attachments/assets/28a77fe2-a468-4246-a897-de8722ef8ec7)

**Comment by Ackites** [comment]
> ![image](https://private-user-images.githubusercontent.com/61149597/355298974-28a77fe2-a468-4246-a897-de8722ef8ec7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MTUxOTAsIm5iZiI6MTcyMjkxNDg5MCwicGF0aCI6Ii82MTE0OTU5Ny8zNTUyOTg5NzQtMjhhNzdmZTItYTQ2OC00MjQ2LWE4OTctZGU4NzIyZWY4ZWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDAzMjgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwYmJiNDdmMTk0OTEyYzM1YWY2ODMyMDFhMzRiYzZkNWQ0MWU1ZmNmOWE2Nzk2MmVkZjgzNTdiYjlmYzg3Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jvLBKor9HOOB-XLwNc6E11INKDDenqg9dnrLllnvx_g)

这没有卡死吧，我这边没法复现，你没有输入任何参数，程序没有运行
