### ISSUE TITLE
反编译出来的文件，没有app.json文件，小程序无法运行

### ISSUE THREAD

**Issue by iBesokuse** [Ackites/KillWxapkg#11]
反编译过程中是没有出现报错，但是目录下就是没有aap.json文件所以小程序无法运行，大佬看看该怎么解决
![image](https://github.com/user-attachments/assets/3b223eb0-8c60-458f-85f7-7287d30106fe)

**Comment by Ackites** [comment]
没有进行解析，只是解包了，使用-restore参数
