### ISSUE TITLE
大佬，那反编译出来的语法错误，是反编译时的错误，是需要自己调试吗，还是说本来程序就这样？

### ISSUE THREAD

**Issue by iBesokuse** [Ackites/KillWxapkg#12]
![image](https://github.com/user-attachments/assets/003f5f6f-648d-43f0-a6ec-2b49243dd9f7)

**Comment by iBesokuse** [comment]
我看了一下是因为这个@特舒符号没有识别出来，所以导致的报错
![image](https://github.com/user-attachments/assets/44bb2e6b-adb7-4311-85de-ac814e2b5210)

**Comment by Ackites** [comment]
> 我看了一下是因为这个@特舒符号没有识别出来，所以导致的报错 ![image](https://private-user-images.githubusercontent.com/76981514/355373640-44bb2e6b-adb7-4311-85de-ac814e2b5210.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzUxOTgsIm5iZiI6MTcyMjkzNDg5OCwicGF0aCI6Ii83Njk4MTUxNC8zNTUzNzM2NDAtNDRiYjJlNmItYWRiNy00MzExLTg1ZGUtYWM4MTRlMmI1MjEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA5MDEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyYzk1MWJkNDQyYTBhOWNhYzEyN2NmMDAxZGExOTNlNTQxZmJkOGZmNjAyZjYxYWZjN2IzMTI3Mzg3ZmQ3ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BbziXZH8tgNmK-o1lxubFtKaQiyud0SDTEX2doT89-Q)

使用-restore解析了吗，能运行吗

**Comment by iBesokuse** [comment]
还是不行，使用-restore后，他不能正常的解析这个路径，你需要手动添加，添加后我还是不能正常运行，唉
![image](https://github.com/user-attachments/assets/f05eaedb-4f62-4f0c-a597-234f10c2c486)

**Comment by Ackites** [comment]
> 还是不行，使用-restore后，他不能正常的解析这个路径，你需要手动添加，添加后我还是不能正常运行，唉 ![image](https://private-user-images.githubusercontent.com/76981514/355388114-f05eaedb-4f62-4f0c-a597-234f10c2c486.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzY2MDQsIm5iZiI6MTcyMjkzNjMwNCwicGF0aCI6Ii83Njk4MTUxNC8zNTUzODgxMTQtZjA1ZWFlZGItNGY2Mi00ZjBjLWE1OTctMjM0ZjEwYzJjNDg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA5MjUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4N2UzZjc5NTk4NDlhMDYzYWQzMWFjMmQ4OWZmYmE2MjQ4OGEzODE4N2ZiMDYzZWYwNjc4YWI0YmY5YWM5NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LyTzGqRkpewDOIUOd6PuwIg34iRLmMKHDdX1VE_s4E8)

开发者工具运行有一些报错很正常，毕竟是反编译的，不是原本的代码，可以用开发者工具打开吧？

**Comment by iBesokuse** [comment]
对的，开发者工具是可以打开的，运行还是不行，肯定需要自己调试
