### ISSUE TITLE
缺少wxml以及wxss文件啊

### ISSUE THREAD

**Issue by clover-cn** [Ackites/KillWxapkg#13]
其他目录是完整的，就是缺少缺少wxml以及wxss文件，是有什么限制吗
![image](https://github.com/user-attachments/assets/e4d48c5a-2533-4701-bae2-315ca11407cb)

**Comment by Ackites** [comment]
> 其他目录是完整的，就是缺少缺少wxml以及wxss文件，是有什么限制吗

使用-restore了吗，如果没有，那可能本身代码就是没有

**Comment by Ackites** [comment]
> 其他目录是完整的，就是缺少缺少wxml以及wxss文件，是有什么限制吗 ![image](https://private-user-images.githubusercontent.com/61149597/355655230-e4d48c5a-2533-4701-bae2-315ca11407cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5OTg1ODIsIm5iZiI6MTcyMjk5ODI4MiwicGF0aCI6Ii82MTE0OTU5Ny8zNTU2NTUyMzAtZTRkNDhjNWEtMjUzMy00NzAxLWJhZTItMzE1Y2ExMTQwN2NiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDAyMzgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjZGMxY2RmMjdjNTRmZDM4MjJkNDc4NDZjZDk2MTg2NmZkODUzZWNiMzdiNjI1NGFkMzVkYzc5ZjYyYjE2NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nf3is2cxVsvIJxI6mXjsZqs-VG967e9SmaYb4lulsUY)

因为有些小程序是采用其他的跨平台框架开发的

**Comment by clover-cn** [comment]
使用了-restore，我用自己的小程序进行测试的，并且是原生

**Comment by Ackites** [comment]
> 使用了-restore，我用自己的小程序进行测试的，并且是原生

可以提供包和截图看看吗

**Comment by Ackites** [comment]
> 使用了-restore，我用自己的小程序进行测试的，并且是原生

对了，是使用的最新版的工具吗😂

**Comment by clover-cn** [comment]
是最新的工具，不过大部分小程序是正常的，有没有可能是小程序基础库过高😂
![image](https://github.com/user-attachments/assets/56cc87f4-d814-41fe-8e8e-5cdad0b43bcb)

**Comment by Ackites** [comment]
> 是最新的工具，不过大部分小程序是正常的，有没有可能是小程序基础库过高😂 ![image](https://private-user-images.githubusercontent.com/61149597/355734750-56cc87f4-d814-41fe-8e8e-5cdad0b43bcb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMTk4MzcsIm5iZiI6MTcyMzAxOTUzNywicGF0aCI6Ii82MTE0OTU5Ny8zNTU3MzQ3NTAtNTZjYzg3ZjQtZDgxNC00MWZlLThlOGUtNWNkYWQwYjQzYmNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA4MzIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjODNjZTU3ZmMyOWMyY2UxNWIxZGI4YTU3ZGVhN2QxM2E2ZGFlZGVhYTgwODExMTM5YmM5NjNmMDFkMzQxMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m94LEu0FTKj_rkyphFKu83gY6X7PXmCgO2gFf1er1bg)

 是有可能的，如果方便的话，可以提供下包吗
