### ISSUE TITLE
js文件没解出来

### ISSUE THREAD

**Issue by RoarRain** [Ackites/KillWxapkg#16]
pages/index 二级目录下没解出来js文件, 只有json,wxml,wxss文件
pages/index/others 三级目录可以解出来
大佬看看是不是解析路径有问题

**Comment by Ackites** [comment]
如果可以的话，可以提供一下wxapkg包和appid

**Comment by bql-bql** [comment]
我也是解出来没有js文件，中间还有两个报错
![b04bd0c61727dbb4f348b1536311470](https://github.com/user-attachments/assets/5befa8f2-0252-4147-9ea2-5a22c934f6c6)

**Comment by Ackites** [comment]
> 我也是解出来没有js文件，中间还有两个报错 ![b04bd0c61727dbb4f348b1536311470](https://private-user-images.githubusercontent.com/168365292/356263721-5befa8f2-0252-4147-9ea2-5a22c934f6c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMzQxODQsIm5iZiI6MTcyMzEzMzg4NCwicGF0aCI6Ii8xNjgzNjUyOTIvMzU2MjYzNzIxLTViZWZhOGYyLTAyNTItNDE0Ny05ZWEyLTVhMjJjOTM0ZjZjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxNjE4MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMWE1MzRjY2NhM2ZlZmUxZGYzMTY1ZjI5ODJiOTI3NTlmMjE1MjgzYmM0YjYzZjNmYzk4OWExZDZkMDVkZDJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bzeyjdl2x4Ek8lY5LnyXi52YqoX7VaTKRhbNSc8MFSM)

如果可以的话，请尽量提供wxapkg包和appid，因为有些版本和开发方式都不一样，不一定能解，后续更新会尽量的兼容

**Comment by bql-bql** [comment]
> > 我也是解出来没有js文件，中间还有两个报错 ![b04bd0c61727dbb4f348b1536311470](https://private-user-images.githubusercontent.com/168365292/356263721-5befa8f2-0252-4147-9ea2-5a22c934f6c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMzQxODQsIm5iZiI6MTcyMzEzMzg4NCwicGF0aCI6Ii8xNjgzNjUyOTIvMzU2MjYzNzIxLTViZWZhOGYyLTAyNTItNDE0Ny05ZWEyLTVhMjJjOTM0ZjZjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxNjE4MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMWE1MzRjY2NhM2ZlZmUxZGYzMTY1ZjI5ODJiOTI3NTlmMjE1MjgzYmM0YjYzZjNmYzk4OWExZDZkMDVkZDJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bzeyjdl2x4Ek8lY5LnyXi52YqoX7VaTKRhbNSc8MFSM)
> 
> 如果可以的话，请尽量提供wxapkg包和appid，因为有些版本和开发方式都不一样，不一定能解，后续更新会尽量的兼容

[wx7696c66d2245d107.zip](https://github.com/user-attachments/files/16550874/wx7696c66d2245d107.zip)
mx冰城小程序

**Comment by RoarRain** [comment]
同上.

**Comment by leishenws** [comment]
小米社区也没解出js文件
