### ISSUE TITLE
加了restore，无法得到还原后的工程结构，是不支持mac么

### ISSUE THREAD

**Issue by rainy-cc** [Ackites/KillWxapkg#19]
请教下大佬，我是自己下载源代码编译的

**Comment by Ackites** [comment]
> 请教下大佬，我是自己下载源代码编译的

有报错吗

**Comment by rainy-cc** [comment]
> > 请教下大佬，我是自己下载源代码编译的
> 
> 有报错吗
提示文件格式化失败
<img width="1344" alt="image" src="https://github.com/user-attachments/assets/bd18c0fc-b887-40eb-84ef-eafdb1991db7">

**Comment by Ackites** [comment]
> > > 请教下大佬，我是自己下载源代码编译的
> > 
> > 
> > 有报错吗
> > 提示文件格式化失败
> 
> <img alt="image" width="1344" src="https://private-user-images.githubusercontent.com/22319417/356875809-bd18c0fc-b887-40eb-84ef-eafdb1991db7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NTk5OTgsIm5iZiI6MTcyMzQ1OTY5OCwicGF0aCI6Ii8yMjMxOTQxNy8zNTY4NzU4MDktYmQxOGMwZmMtYjg4Ny00MGViLTg0ZWYtZWFmZGIxOTkxZGI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDEwNDgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3ZWRlOWQ1ZmFmNmM4YTQ0NTEwZjMzY2U4OGNhZDgzMjFjOWE4Y2I5YjcwNmQ4M2Q2ZWViYjE5MWQ0NTFjOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o3Ne3S5ONGRrEnskjYH1IoTW2v-8_Tgg7JFs8Rjm-VI">

我这边没有mac的环境，也不好方便测试，如果可以的话你也可以提PR🤦‍♂️

**Comment by Ackites** [comment]
> > > 请教下大佬，我是自己下载源代码编译的
> > 
> > 
> > 有报错吗
> > 提示文件格式化失败
> 
> <img alt="image" width="1344" src="https://private-user-images.githubusercontent.com/22319417/356875809-bd18c0fc-b887-40eb-84ef-eafdb1991db7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NzQ4NjUsIm5iZiI6MTcyMzQ3NDU2NSwicGF0aCI6Ii8yMjMxOTQxNy8zNTY4NzU4MDktYmQxOGMwZmMtYjg4Ny00MGViLTg0ZWYtZWFmZGIxOTkxZGI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDE0NTYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwZmRmODU3MjNjMzQyYTYwMTVkODk2YzFlZGJmMzU0OGU1YWFmZDQzYzAyZWNlZTg5YzQyOTkxNjkxNGFmNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1LTowQmEAVAK6aSDRl_pw1PEE8Xnfv5neoTeoIQFlm4">

提供一下wxapkg文件和id吧
