### ISSUE TITLE
找不到文件

### ISSUE THREAD

**Issue by djkloop** [Ackites/KillWxapkg#2]
![QQ_1721903549372](https://github.com/user-attachments/assets/ed5be2f3-8df8-4553-bc50-56bb1754a30e)
#### 我确定它肯定有这个文件夹的
![QQ_1721903645060](https://github.com/user-attachments/assets/5d634642-5222-4f04-a7dd-00e7bad979c5)

**Comment by Ackites** [comment]
> ![QQ_1721903549372](https://private-user-images.githubusercontent.com/21050914/352072938-ed5be2f3-8df8-4553-bc50-56bb1754a30e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MDQxNDIsIm5iZiI6MTcyMTkwMzg0MiwicGF0aCI6Ii8yMTA1MDkxNC8zNTIwNzI5MzgtZWQ1YmUyZjMtOGRmOC00NTUzLWJjNTAtNTZiYjE3NTRhMzBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDEwMzcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxZmY2NGMxMTk4NDU1MjA4ODg3MWQ4M2MxMDg1MGExMDZkM2VkMDBlYjliYjZkZGM5MWEyNTM4NDQyODcxNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UI1LQBkzxBKEXAx_EFMQbMIEOZkqkwGFbWbLZgEhzps)
> 
> #### 我确定它肯定有这个文件夹的
> ![QQ_1721903645060](https://private-user-images.githubusercontent.com/21050914/352073337-5d634642-5222-4f04-a7dd-00e7bad979c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MDQxNDIsIm5iZiI6MTcyMTkwMzg0MiwicGF0aCI6Ii8yMTA1MDkxNC8zNTIwNzMzMzctNWQ2MzQ2NDItNTIyMi00ZjA0LWE3ZGQtMDBlN2JhZDk3OWM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDEwMzcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjMjRhNWQ0ZmJlODBjYzkxOGE0NjkxNzMzYjQ1NTljYjQ3MjJlMzM3NDc5Yzk0MzMwMDJiMDIzNTgxYzI5N2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.veTE0uprPg4fVzG39Kc1DRVwVQQT3bjaPsOY0Hw2JLg)

可以先把里面wxapkg单独复制出来

**Comment by Ackites** [comment]
> > ![QQ_1721903549372](https://private-user-images.githubusercontent.com/21050914/352072938-ed5be2f3-8df8-4553-bc50-56bb1754a30e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MDQxNDIsIm5iZiI6MTcyMTkwMzg0MiwicGF0aCI6Ii8yMTA1MDkxNC8zNTIwNzI5MzgtZWQ1YmUyZjMtOGRmOC00NTUzLWJjNTAtNTZiYjE3NTRhMzBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDEwMzcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxZmY2NGMxMTk4NDU1MjA4ODg3MWQ4M2MxMDg1MGExMDZkM2VkMDBlYjliYjZkZGM5MWEyNTM4NDQyODcxNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UI1LQBkzxBKEXAx_EFMQbMIEOZkqkwGFbWbLZgEhzps)
> > #### 我确定它肯定有这个文件夹的
> > ![QQ_1721903645060](https://private-user-images.githubusercontent.com/21050914/352073337-5d634642-5222-4f04-a7dd-00e7bad979c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MDQxNDIsIm5iZiI6MTcyMTkwMzg0MiwicGF0aCI6Ii8yMTA1MDkxNC8zNTIwNzMzMzctNWQ2MzQ2NDItNTIyMi00ZjA0LWE3ZGQtMDBlN2JhZDk3OWM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDEwMzcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjMjRhNWQ0ZmJlODBjYzkxOGE0NjkxNzMzYjQ1NTljYjQ3MjJlMzM3NDc5Yzk0MzMwMDJiMDIzNTgxYzI5N2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.veTE0uprPg4fVzG39Kc1DRVwVQQT3bjaPsOY0Hw2JLg)
> 
> 可以先把里面wxapkg单独复制出来

文件夹下需要存在.wxapkg文件😂, 没做递归检查哈, 还有就是路径有空格, 给加上"xx"

**Comment by panjianning** [comment]
windows貌似没发现有wxapkg

**Comment by Ackites** [comment]
> windows貌似没发现有wxapkg

什么意思，没找到？需要有运行小程序了，才会有wxapkg包下载下来

**Comment by panjianning** [comment]
> > windows貌似没发现有wxapkg
> 
> 什么意思，没找到？需要有运行小程序了，才会有wxapkg包下载下来

运行了的，applet文件夹里一堆小程序id的文件夹，里面都没有wxapkg

**Comment by Ackites** [comment]
> > > windows貌似没发现有wxapkg
> > 
> > 
> > 什么意思，没找到？需要有运行小程序了，才会有wxapkg包下载下来
> 
> 运行了的，applet文件夹里一堆小程序id的文件夹，里面都没有wxapkg

请注意路径。。。关于获取微信小程序AppID我已经写的很清楚了，红色箭头部分，从微信打开文件夹后，你要再返回上一层

**Comment by panjianning** [comment]
> > > > windows貌似没发现有wxapkg
> > > 
> > > 
> > > 什么意思，没找到？需要有运行小程序了，才会有wxapkg包下载下来
> > 
> > 
> > 运行了的，applet文件夹里一堆小程序id的文件夹，里面都没有wxapkg
> 
> 请注意路径。。。关于获取微信小程序AppID我已经写的很清楚了，红色箭头部分，从微信打开文件夹后，你要再返回上一层

全局搜都不到任何wxapkg

**Comment by panjianning** [comment]
> > > > windows貌似没发现有wxapkg
> > > 
> > > 
> > > 什么意思，没找到？需要有运行小程序了，才会有wxapkg包下载下来
> > 
> > 
> > 运行了的，applet文件夹里一堆小程序id的文件夹，里面都没有wxapkg
> 
> 请注意路径。。。关于获取微信小程序AppID我已经写的很清楚了，红色箭头部分，从微信打开文件夹后，你要再返回上一层

啊，找到了
