### ISSUE TITLE
加上 "-restore" 参数会报错

### ISSUE THREAD

**Issue by depycode** [Ackites/KillWxapkg#20]
```
2024/08/10 19:44:21 Config file processed: test\app-config.json
2024/08/10 19:44:22 Splitting "test\app-service.js" done.
runtime: VirtualAlloc of 940187648 bytes failed with errno=1455
fatal error: out of memory

runtime stack:
runtime.throw({0x4fed07?, 0xc0da8be000?})
        /opt/hostedtoolcache/go/1.22.5/x64/src/runtime/panic.go:1023 +0x65 fp=0x9bc1fff678 sp=0x9bc1fff648 pc=0x6ce65
runtime.sysUsedOS(0xc0b99ee000, 0x380a2000)
        /opt/hostedtoolcache/go/1.22.5/x64/src/runtime/mem_windows.go:83 +0x1bb fp=0x9bc1fff6d8 sp=0x9bc1fff678 pc=0x4b8db
runtime.sysUsed(...)
```

**Comment by Ackites** [comment]
> ```
> 2024/08/10 19:44:21 Config file processed: test\app-config.json
> 2024/08/10 19:44:22 Splitting "test\app-service.js" done.
> runtime: VirtualAlloc of 940187648 bytes failed with errno=1455
> fatal error: out of memory
> 
> runtime stack:
> runtime.throw({0x4fed07?, 0xc0da8be000?})
>         /opt/hostedtoolcache/go/1.22.5/x64/src/runtime/panic.go:1023 +0x65 fp=0x9bc1fff678 sp=0x9bc1fff648 pc=0x6ce65
> runtime.sysUsedOS(0xc0b99ee000, 0x380a2000)
>         /opt/hostedtoolcache/go/1.22.5/x64/src/runtime/mem_windows.go:83 +0x1bb fp=0x9bc1fff6d8 sp=0x9bc1fff678 pc=0x4b8db
> runtime.sysUsed(...)
> ```

内存不足了，-restore解析有一定的性能要求
