### ISSUE TITLE
failed to start hook

### ISSUE THREAD

**Issue by jiyzhang** [Ackites/KillWxapkg#22]
每次执行KillWxapkg.exe -hook 都会报错，有什么 troubleshooting 的方法吗？

```
C:\github\KillWxapkg>KillWxapkg.exe -hook

 _   __ _ _ _  __      __                 _
| | / /(_) | | \ \    / /                | |        
| |/ /  _| | |  \ \  / /   __  ____ _ ___| | ____ _ 
|    \ | | | |   \ \/ /   / / / / _  / __| |/ /  ' \
| |\  \| | | |    \  /   / /_/ / (_| \__ \   <| | | |
\_| \_/_|_|_|     \/    \__,_|\__,_|___/_|\_\_| |_|

             Wxapkg Decompiler Tool v2.2.1
    
Error injecting into WeChat PID 12656: process with pid 12656 either refused to load frida-agent, or terminated during injection
Injected into WeChat instance PID: 12656, Version: 11159
[1484] WARNING: failed to remove temporary directory: C:\Users\test\AppData\Local\Temp\_MEI14842

Failed to remove temporary directory: remove C:\Users\test\AppData\Local\Temp\KillwxapkgHook1732696427\win.exe: Access is denied.
```

**Comment by Ackites** [comment]
> 每次执行KillWxapkg.exe -hook 都会报错，有什么 troubleshooting 的方法吗？
> 
> ```
> C:\github\KillWxapkg>KillWxapkg.exe -hook
> 
>  _   __ _ _ _  __      __                 _
> | | / /(_) | | \ \    / /                | |        
> | |/ /  _| | |  \ \  / /   __  ____ _ ___| | ____ _ 
> |    \ | | | |   \ \/ /   / / / / _  / __| |/ /  ' \
> | |\  \| | | |    \  /   / /_/ / (_| \__ \   <| | | |
> \_| \_/_|_|_|     \/    \__,_|\__,_|___/_|\_\_| |_|
> 
>              Wxapkg Decompiler Tool v2.2.1
>     
> Error injecting into WeChat PID 12656: process with pid 12656 either refused to load frida-agent, or terminated during injection
> Injected into WeChat instance PID: 12656, Version: 11159
> [1484] WARNING: failed to remove temporary directory: C:\Users\test\AppData\Local\Temp\_MEI14842
> 
> Failed to remove temporary directory: remove C:\Users\test\AppData\Local\Temp\KillwxapkgHook1732696427\win.exe: Access is denied.
> ```

用管理员权限允许试试
