### ISSUE TITLE
-repack 之后微信提示清理缓存，repack没用

### ISSUE THREAD

**Issue by Bre8gljm20sendaWofqeoj8biu6odhouse** [Ackites/KillWxapkg#24]
repack之后，微信打开小程序直接就告诉我清理缓存，应该是检测到修改了直接不让运行，有什么方法可以处理这个问题吗

**Comment by Ackites** [comment]
> repack之后，微信打开小程序直接就告诉我清理缓存，应该是检测到修改了直接不让运行，有什么方法可以处理这个问题吗

可以提供截图吗
