### ISSUE TITLE
使用太复杂建议简化命令

### ISSUE THREAD

**Issue by bigsinger** [Ackites/KillWxapkg#25]
建议：默认输入appid或文件名或文件路径都可以自动识别并反编译。

**Comment by Ackites** [comment]
> 建议：默认输入appid或文件名或文件路径都可以自动识别并反编译。

没理解到底是哪里复杂🤦,不是只需要输入一个id,和文件存放位置就可以了吗

**Comment by qqeip** [comment]
in 目录不能有空格  带空格要用"" 折腾大半天

**Comment by Ackites** [comment]
> in 目录不能有空格 带空格要用"" 折腾大半天
这不都写有说明吗🤦
