### ISSUE TITLE
保存页面json的时候会因为路径问题异常

### ISSUE THREAD

**Issue by qinjianwei** [Ackites/KillWxapkg#26]
![image](https://github.com/user-attachments/assets/b2f89ff4-ee61-425d-819b-60339fa35f01)

此时的路径是out_restore_pretty_weChat\plugin-private:\wx404312bef23fd799\components\popup\index.json，plugin-private后面多了一个“：”
![image](https://github.com/user-attachments/assets/f12c4b70-5d12-47d8-86dd-ca8b7a26738a)

**Comment by Ackites** [comment]
> ![image](https://private-user-images.githubusercontent.com/17981557/357742425-b2f89ff4-ee61-425d-819b-60339fa35f01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NDg4NzMsIm5iZiI6MTcyMzY0ODU3MywicGF0aCI6Ii8xNzk4MTU1Ny8zNTc3NDI0MjUtYjJmODlmZjQtZWU2MS00MjVkLTgxOWItNjAzMzlmYTM1ZjAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDE1MTYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxNTBiYzJlNGIzZTQzYmE4MjczNTRjYjBkZTg0M2Y4M2RmY2VmNDNhMWI2Mzc3ODdkYjEwN2NkZjQwN2IxNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uHc-MhalS5mFIOslI4r3MjHqZKp8tzjr8W9aPLhlRTI)
> 
> 此时的路径是out_restore_pretty_weChat\plugin-private:\wx404312bef23fd799\components\popup\index.json，plugin-private后面多了一个“：” ![image](https://private-user-images.githubusercontent.com/17981557/357743134-f12c4b70-5d12-47d8-86dd-ca8b7a26738a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NDg4NzMsIm5iZiI6MTcyMzY0ODU3MywicGF0aCI6Ii8xNzk4MTU1Ny8zNTc3NDMxMzQtZjEyYzRiNzAtNWQxMi00N2Q4LTg2ZGQtY2E4YjdhMjY3MzhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDE1MTYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNjEzN2E3NDljMzI5NzI3ZmZjZjQ2ZmUxZWQ3OWIyNjE3NDBjMGJlMzEwYjlmOWYzYzdhNWMxOTUyZTBmOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-V28L27uudQ6edQO0RSYTh1HRAfV7-wrg3CzXEj7Nq8)

是使用的最新版吗

**Comment by qinjianwei** [comment]
![image](https://github.com/user-attachments/assets/792990b8-5531-4dec-836b-0b2fb54710fc)
前天提交的版本，路径应该是插件的

**Comment by Ackites** [comment]
> ![image](https://private-user-images.githubusercontent.com/17981557/358165591-792990b8-5531-4dec-836b-0b2fb54710fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MTMxMDIsIm5iZiI6MTcyMzcxMjgwMiwicGF0aCI6Ii8xNzk4MTU1Ny8zNTgxNjU1OTEtNzkyOTkwYjgtNTUzMS00ZGVjLTgzNmItMGIyZmI1NDcxMGZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDA5MDY0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmNTdkNTQ2NzlhMDM5MjcwYmVhNjgzYTIwNTMzYjY3ODQ3NWE3YmU4YWVkYmIyYzg3NmFlYzM2MjE4NTdlMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zRMnECjdsQeuXwwk6OxMeo0OUbzgXgDnT_ynLBu5tJI) 前天提交的版本，路径应该是插件的

在最新版是已经解决了这个问题的，如果可以的话提供一下wxapkg文件和id

**Comment by qinjianwei** [comment]
最新的源码也是如此  id wx898cb4b08963dccb 
[pkg.zip](https://github.com/user-attachments/files/16623729/pkg.zip)

**Comment by qinjianwei** [comment]
linux应该没有关系，windows不支持路径中带有:
