### ISSUE TITLE
wxml文件未反编译，内容是空的

### ISSUE THREAD

**Issue by TenderHeart955** [Ackites/KillWxapkg#27]
![QQ截图20240814165930](https://github.com/user-attachments/assets/c2764e8e-f89c-4ad5-ae9f-00c94a6c37c4)
所有的的wxml文件都是初始化的状态，似乎没往里面写入

**Comment by TenderHeart955** [comment]
![QQ截图20240814180031](https://github.com/user-attachments/assets/bed766db-63e5-4721-a18f-36b23cedeb1b)
解密解包之后的文件还在，还原源代码工程目录结构之后就无了 QWQ

**Comment by Ackites** [comment]
> ![QQ截图20240814165930](https://private-user-images.githubusercontent.com/49381789/357748189-c2764e8e-f89c-4ad5-ae9f-00c94a6c37c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NDg5NzIsIm5iZiI6MTcyMzY0ODY3MiwicGF0aCI6Ii80OTM4MTc4OS8zNTc3NDgxODktYzI3NjRlOGUtZjg5Yy00YWQ1LWFlOWYtMDBjOTRhNmMzN2M0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDE1MTc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0YWUyYTNkYTE3NGZiYWJkNTM4NTc5YjIwMTM5MTkxMDk0NTYzZTgzYjc2MTViYmQ1MTUyZDI3ZWRhN2RiMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4KVWaw06HNUjw00Y4dHbRwshIOc2puXn4W58OBk3ffw) 所有的的wxml文件都是初始化的状态，似乎没往里面写入

没有解析,使用-restore参数

**Comment by TenderHeart955** [comment]
大哥  第一张图就是用了-restore参数的，wxml文件里是空的。第二张图我把-restore参数去掉了在debug，发现是还原目录这一步有问题，wxc9e7bd2dfd30faad  你可以试一下

**Comment by Ackites** [comment]
> 大哥 第一张图就是用了-restore参数的，wxml文件里是空的。第二张图我把-restore参数去掉了在debug，发现是还原目录这一步有问题，wxc9e7bd2dfd30faad 你可以试一下

提供一下wxapkg

**Comment by TenderHeart955** [comment]
[wxc9e7bd2dfd30faad.zip](https://github.com/user-attachments/files/16621179/wxc9e7bd2dfd30faad.zip)

**Comment by Ackites** [comment]
> [wxc9e7bd2dfd30faad.zip](https://github.com/user-attachments/files/16621179/wxc9e7bd2dfd30faad.zip)



> [wxc9e7bd2dfd30faad.zip](https://github.com/user-attachments/files/16621179/wxc9e7bd2dfd30faad.zip)

这个目前没办法解决，不知道这个是用什么框架开发的，没办法提取

**Comment by TenderHeart955** [comment]
好像是腾讯官方出的  tdesign 框架

**Comment by Ackites** [comment]
> 好像是腾讯官方出的 tdesign 框架

我的意思是它不是原生的，是用了其他的跨平台框架

**Comment by TenderHeart955** [comment]
> > 好像是腾讯官方出的 tdesign 框架
> 
> 我的意思是它不是原生的，是用了其他的跨平台框架

好吧， js啥的都是完整的  页面没有 哈哈哈哈 凑合看吧  感谢🙏
