### ISSUE TITLE
我尝试反编译了几个小程序，编译出结果，但是运行不起来。是我mac的电脑原因吗，加密包有问题？你们有成功的吗？

### ISSUE THREAD

**Issue by 1372143376** [Ackites/KillWxapkg#28]
<img width="922" alt="image" src="https://github.com/user-attachments/assets/c1592216-3c31-4db9-895c-cc520ea55659">

**Comment by 1372143376** [comment]
wx723bb5bb25362f6c
[779.zip](https://github.com/user-attachments/files/16610620/779.zip)

**Comment by jqqjj** [comment]
win今天刚接触，可用没毛病

**Comment by Ackites** [comment]
> wx723bb5bb25362f6c [779.zip](https://github.com/user-attachments/files/16610620/779.zip)
> 
> 麻烦码主，尝试下

没有文件

**Comment by 1372143376** [comment]
[779.zip](https://github.com/user-attachments/files/16622006/779.zip)
@Ackites

**Comment by Mrrrrr10** [comment]
同样的问题

**Comment by Mrrrrr10** [comment]
很多包都解出来都是没有app.json的... up主看看呀 @Ackites

**Comment by Mrrrrr10** [comment]
[737.zip](https://github.com/user-attachments/files/16727215/737.zip)
@Ackites

**Comment by Ackites** [comment]
> 很多包都解出来都是没有app.json的... up主看看呀 @Ackites

提供一下id和截图，检查一下是否正确使用，使用-restore参数了吗

**Comment by Mrrrrr10** [comment]
> > 很多包都解出来都是没有app.json的... up主看看呀 @Ackites
> 
> 提供一下id和截图，检查一下是否正确使用，使用-restore参数了吗

1、id=wx71d589ea01ce3321，包https://github.com/user-attachments/files/16727215/737.zip
2、命令：KillWxapkg_2.3.2_windows_amd64.exe -id="wx2e19fac8dc4cb5be" -in="K:\software\applet\wx2e19fac8dc4cb5be" -out="K:\software\applet\wx2e19fac8dc4cb5be_2" -restore
3、过程没报错，结果有app.json
4、微信开发者工具，打开，运行报错：[ app.json 文件内容错误] app.json: "__plugin__/wx4645f4f355c0521a/pages/index/index" 在 ["subPackages"][0] 中重复(env: Windows,mp,1.06.2407120; lib: 3.5.4)
@Ackites 
![image](https://github.com/user-attachments/assets/d82d8830-d7cb-4fae-8734-680a7662788b)

**Comment by Mrrrrr10** [comment]
> > > 很多包都解出来都是没有app.json的... up主看看呀 @Ackites
> > 
> > 
> > 提供一下id和截图，检查一下是否正确使用，使用-restore参数了吗
> 
> 1、id=wx71d589ea01ce3321，包https://github.com/user-attachments/files/16727215/737.zip 2、命令：KillWxapkg_2.3.2_windows_amd64.exe -id="wx71d589ea01ce3321" -in="C:\Users\K\Documents\WeChat Files\Applet\wx71d589ea01ce3321\737" -out="K:\software\applet\wx71d589ea01ce3321" -restore 3、过程没报错，结果有app.json 4、微信开发者工具，打开，运行报错：[ app.json 文件内容错误] app.json: "**plugin**/wx4645f4f355c0521a/pages/index/index" 在 ["subPackages"][0] 中重复(env: Windows,mp,1.06.2407120; lib: 3.5.4) @Ackites ![image](https://private-user-images.githubusercontent.com/35874505/360981905-d82d8830-d7cb-4fae-8734-680a7662788b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjgwOTksIm5iZiI6MTcyNDQyNzc5OSwicGF0aCI6Ii8zNTg3NDUwNS8zNjA5ODE5MDUtZDgyZDg4MzAtZDdjYi00ZmFlLTg3MzQtNjgwYTc2NjI3ODhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDE1NDMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiZmRlNjg2MzlhNDM1MzJhNDE1NDVlNzlmODBhZjE1MjFhNTIwNTZjOGM3ODYyZTVkZWMxZmU5NmMxYzcyM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q5oAqprv3qwqsi8uGy8ZMkTc_E6oygeziPACPZeGLbg)

这里的问题比较明显，就是subPackages.pages存在plugins，这个plugins不应该在pages里面的，然后，我把plugins去掉，即：
```
"subPackages": [
        {
            "root": "added/plugin-nav/",
            "pages": [
                "pages/index/index"
            ]
        },
```
重新编译，再次报错，来了3个更迷的

第一个ERROR：[] 以 '__' 为开头和结尾的目录为保留目录；donutAuthorize__ 是保留目录。added\plugin-nav\__plugin__ 目录下的所有文件将会被忽略。(env: Windows,mp,1.06.2407120; lib: 3.5.4)

第二个ERROR：[ WXSS 文件编译错误] 
./pages/linedetail/linedetail.wxss(148:34): unexpected `(` at pos 2371(env: Windows,mp,1.06.2407120; lib: 3.5.4)

第三个ERROR：[ WXML 文件编译错误] ./pages/components/drag-view/index.wxml
unexpected character `$`
> 1 | 	<view class="drag-layout layout-class" options="<nil>" $gdc="0x82cd20" $wxs:bindtouchend="0x82cd20" $wxs:bindtouchstart="0x82cd20" $wxs:catchtouchmove="0x82cd20" $wxs:change:options="0x82cd20">
    | 	                                                     ^
  2 | 		<slot>		</slot>
  3 | 	</view>
  4 | 
at files://pages/components/drag-view/index.wxml#1(env: Windows,mp,1.06.2407120; lib: 3.5.4)

@Ackites  进度卡在这了

**Comment by Ackites** [comment]
> > > > 很多包都解出来都是没有app.json的... up主看看呀 @Ackites
> > > 
> > > 
> > > 提供一下id和截图，检查一下是否正确使用，使用-restore参数了吗
> > 
> > 
> > 1、id=wx71d589ea01ce3321，包https://github.com/user-attachments/files/16727215/737.zip 2、命令：KillWxapkg_2.3.2_windows_amd64.exe -id="wx71d589ea01ce3321" -in="C:\Users\K\Documents\WeChat Files\Applet\wx71d589ea01ce3321\737" -out="K:\software\applet\wx71d589ea01ce3321" -restore 3、过程没报错，结果有app.json 4、微信开发者工具，打开，运行报错：[ app.json 文件内容错误] app.json: "**plugin**/wx4645f4f355c0521a/pages/index/index" 在 ["subPackages"][0] 中重复(env: Windows,mp,1.06.2407120; lib: 3.5.4) @Ackites ![image](https://private-user-images.githubusercontent.com/35874505/360981905-d82d8830-d7cb-4fae-8734-680a7662788b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjgwOTksIm5iZiI6MTcyNDQyNzc5OSwicGF0aCI6Ii8zNTg3NDUwNS8zNjA5ODE5MDUtZDgyZDg4MzAtZDdjYi00ZmFlLTg3MzQtNjgwYTc2NjI3ODhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDE1NDMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiZmRlNjg2MzlhNDM1MzJhNDE1NDVlNzlmODBhZjE1MjFhNTIwNTZjOGM3ODYyZTVkZWMxZmU5NmMxYzcyM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q5oAqprv3qwqsi8uGy8ZMkTc_E6oygeziPACPZeGLbg)
> 
> 这里的问题比较明显，就是subPackages.pages存在plugins，这个plugins不应该在pages里面的，然后，我把plugins去掉，即：
> 
> ```
> "subPackages": [
>         {
>             "root": "added/plugin-nav/",
>             "pages": [
>                 "pages/index/index"
>             ]
>         },
> ```
> 
> 重新编译，再次报错，来了3个更迷的
> 
> 第一个ERROR：[] 以 '**' 为开头和结尾的目录为保留目录；donutAuthorize** 是保留目录。added\plugin-nav__plugin__ 目录下的所有文件将会被忽略。(env: Windows,mp,1.06.2407120; lib: 3.5.4)
> 
> 第二个ERROR：[ WXSS 文件编译错误] ./pages/linedetail/linedetail.wxss(148:34): unexpected `(` at pos 2371(env: Windows,mp,1.06.2407120; lib: 3.5.4)
> 
> 第三个ERROR：[ WXML 文件编译错误] ./pages/components/drag-view/index.wxml unexpected character `$`
> 
> > 1 | 	<view class="drag-layout layout-class" options="" $gdc="0x82cd20" $wxs:bindtouchend="0x82cd20" $wxs:bindtouchstart="0x82cd20" $wxs:catchtouchmove="0x82cd20" $wxs:change:options="0x82cd20">
> > | 	                                                     ^
> > 2 | 				
> > 3 | 	
> > 4 |
> > at files://pages/components/drag-view/index.wxml#1(env: Windows,mp,1.06.2407120; lib: 3.5.4)
> 
> @Ackites 进度卡在这了

工具存在的问题已经更新了，只能保证微信开发者工具能打开，不能确保正常运行，毕竟不是一比一还原代码，而且可能并不是原生开发
