### ISSUE TITLE
解包失败，这是为什么呢

### ISSUE THREAD

**Issue by wuyu-sile** [Ackites/KillWxapkg#30]
![image](https://github.com/user-attachments/assets/70dc7c48-d80c-4e41-84a5-b0961d4301c3)

**Comment by wuyu-sile** [comment]
[233.zip](https://github.com/user-attachments/files/16622185/233.zip)
id=233
麻烦看一下，试了其他一些解包工具确实也不行

**Comment by Ackites** [comment]
> [233.zip](https://github.com/user-attachments/files/16622185/233.zip) id=233 麻烦看一下，试了其他一些解包工具确实也不行

id 123？这肯定不是正确的呀，你输入参数是123？。

**Comment by Ackites** [comment]
我这边测试是正常的，你用法错了。。。id 没输入正确，wx6718e4b1e9cce6b2
