### ISSUE TITLE
反编译出现Error asserting function for $gwx

### ISSUE THREAD

**Issue by qinjianwei** [Ackites/KillWxapkg#32]
![image](https://github.com/user-attachments/assets/9d4bb3d0-e51a-45bd-b307-46d61889d522)

**Comment by Ackites** [comment]
> ![image](https://private-user-images.githubusercontent.com/17981557/358225958-9d4bb3d0-e51a-45bd-b307-46d61889d522.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MzI0ODQsIm5iZiI6MTcyMzczMjE4NCwicGF0aCI6Ii8xNzk4MTU1Ny8zNTgyMjU5NTgtOWQ0YmIzZDAtZTUxYS00NWJkLWIzMDctNDZkNjE4ODlkNTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDE0Mjk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyMmFjYmIzNGJjYzFhNDZjZDFjZDA5NWUwZmFkNmQ1NGJkMTI4NzkyZjE0YjIwNTQ2MGUyMGJjNTdiNGIzMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rGDPAXir_BSkeBociPNmZogBzAYh3Yj2H6_P2RUYaE0)

已经修复，更新最新版本
