### ISSUE TITLE
解包不出来wxml是什么情况

### ISSUE THREAD

**Issue by Debug-boy** [Ackites/KillWxapkg#34]

**Comment by Ackites** [comment]
提供一下wxapkg和id

**Comment by Debug-boy** [comment]
id=wx2e19fac8dc4cb5be
[__APP__.zip](https://github.com/user-attachments/files/16687350/__APP__.zip)

**Comment by Debug-boy** [comment]
栓q

**Comment by Ackites** [comment]
> id=wx2e19fac8dc4cb5be [**APP**.zip](https://github.com/user-attachments/files/16687350/__APP__.zip)

这个小程序不是原生开发，没办法解析
