### ISSUE TITLE
macos 13.6.7 (22G720) intel芯片无法运行amd64程序

### ISSUE THREAD

**Issue by jarryyen** [Ackites/KillWxapkg#38]
作者您好，您编译的 macos amd64位版本在 macOS 13.6.7 (22G720) intel CPU下无法运行

辛苦您看一下

非常感谢您的帮助

**Comment by Ackites** [comment]
> 作者您好，您编译的 macos amd64位版本在 macOS 13.6.7 (22G720) intel CPU下无法运行
> 
> 辛苦您看一下
> 
> 非常感谢您的帮助

有错误吗，可以提供截图吗

**Comment by jarryyen** [comment]
> > 作者您好，您编译的 macos amd64位版本在 macOS 13.6.7 (22G720) intel CPU下无法运行
> > 辛苦您看一下
> > 非常感谢您的帮助
> 
> 有错误吗，可以提供截图吗

<img width="244" alt="SCR-20240831-obih" src="https://github.com/user-attachments/assets/d56eeb23-7510-4c1a-99bc-a33295bfa9b1">

好的 ， arm会提示CPU不对是没问题的，amd无提示。

谢谢，辛苦

**Comment by Ackites** [comment]
> > > 作者您好，您编译的 macos amd64位版本在 macOS 13.6.7 (22G720) intel CPU下无法运行
> > > 辛苦您看一下
> > > 非常感谢您的帮助
> > 
> > 
> > 有错误吗，可以提供截图吗
> 
> <img alt="SCR-20240831-obih" width="244" src="https://private-user-images.githubusercontent.com/11880312/363398175-d56eeb23-7510-4c1a-99bc-a33295bfa9b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MDYwNDMsIm5iZiI6MTcyNjgwNTc0MywicGF0aCI6Ii8xMTg4MDMxMi8zNjMzOTgxNzUtZDU2ZWViMjMtNzUxMC00YzFhLTk5YmMtYTMzMjk1YmZhOWIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA0MTU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkYTE1Y2Q3MjI0MjVhZmQyYzQ1ZGIzYWM5ZWY2MTA0MDhkMzM4OTlkZTk1YzM1MjllNjY3MjYzMGM0NzQ2ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oZTEY-gRYxPfe670ipcUzc_HOLaMHhgbSOLF6NDiKEM">
> 好的 ， arm会提示CPU不对是没问题的，amd无提示。
> 
> 谢谢，辛苦

https://github.com/Ackites/KillWxapkg/issues/39#issuecomment-2325983015
