### ISSUE TITLE
命令太过复杂

### ISSUE THREAD

**Issue by lukesyy** [Ackites/KillWxapkg#4]
不知道为啥不对
![微信截图_20240726165159](https://github.com/user-attachments/assets/e747637a-2669-4abb-ad01-c8f5039054cf)
![微信截图_20240726165612](https://github.com/user-attachments/assets/fdc4f2e8-e7b6-4500-9f82-2bb4c094329d)

**Comment by Ackites** [comment]
> 不知道为啥不对 ![微信截图_20240726165159](https://private-user-images.githubusercontent.com/70319988/352464546-e747637a-2669-4abb-ad01-c8f5039054cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5ODU2NjEsIm5iZiI6MTcyMTk4NTM2MSwicGF0aCI6Ii83MDMxOTk4OC8zNTI0NjQ1NDYtZTc0NzYzN2EtMjY2OS00YWJiLWFkMDEtYzhmNTAzOTA1NGNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDA5MTYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyNDA4NGZhZWNiZTVjN2M5MzQ0MDNkNzM3NWJkMjdmYmEwMmJmMTY2NzMwM2E2NWM2NGMyOTdlZmEwNTk3OTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QX5INnbEIiujI-8E9pgOevJPgVsPEtdkmMFqerklsuU) ![微信截图_20240726165612](https://private-user-images.githubusercontent.com/70319988/352464567-fdc4f2e8-e7b6-4500-9f82-2bb4c094329d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5ODU2NjEsIm5iZiI6MTcyMTk4NTM2MSwicGF0aCI6Ii83MDMxOTk4OC8zNTI0NjQ1NjctZmRjNGYyZTgtZTdiNi00NTAwLTlmODItMmJiNGMwOTQzMjlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDA5MTYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlMDFlODJlODBkOTYwZDQwOWFiNjY2MzQzNGVhNWVmZTIyNzc2ZTMxNDFkN2I0Yzc4MWEwZGRiYzNmNDA2NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IzlFKkO2yVrsgevDUwPCBYtsHR-mCkmhfRp0Vg_Wloo)

都没有运行程序怎么会对呢😂, 
![6](https://github.com/user-attachments/assets/4bd0bf61-dffa-4afe-8954-9b95494e18f7)
