### ISSUE TITLE
部分wxml解不出来

### ISSUE THREAD

**Issue by WolfCanglong** [Ackites/KillWxapkg#40]
![QQ截图20240904123903](https://github.com/user-attachments/assets/1db4763b-610f-46aa-b810-9abd9ba2ae47)
wxfb65081e88b0f684
[__APP__.zip](https://github.com/user-attachments/files/16860864/__APP__.zip)

大部分wxml还是可以解的 
看app-wxss.js里面代码是在的 函数好像混淆了

**Comment by Ackites** [comment]
> ![QQ截图20240904123903](https://private-user-images.githubusercontent.com/40590525/364225645-1db4763b-610f-46aa-b810-9abd9ba2ae47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MDU3ODEsIm5iZiI6MTcyNjgwNTQ4MSwicGF0aCI6Ii80MDU5MDUyNS8zNjQyMjU2NDUtMWRiNDc2M2ItNjEwZi00NmFhLWI4MTAtOWFiZDliYTJhZTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA0MTEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0ZmU4OTE0NTBkNzNkYjI0MTViM2VmNzZlNmZlMTE4MTViMWQ3ZWMzNGFiMzUwYzE4NTJmNzNjN2Y2OTViMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.U5vcJQqkt5vx-N6Tu_tzjVvAUjcTF_Z3DKtgjjspFOk) wxfb65081e88b0f684 [**APP**.zip](https://github.com/user-attachments/files/16860864/__APP__.zip)
> 
> 大部分wxml还是可以解的 看app-wxss.js里面代码是在的 函数好像混淆了

图片中错误属正常，不影响解析结果

**Comment by WolfCanglong** [comment]
> > ![QQ截图20240904123903](https://private-user-images.githubusercontent.com/40590525/364225645-1db4763b-610f-46aa-b810-9abd9ba2ae47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MDU3ODEsIm5iZiI6MTcyNjgwNTQ4MSwicGF0aCI6Ii80MDU5MDUyNS8zNjQyMjU2NDUtMWRiNDc2M2ItNjEwZi00NmFhLWI4MTAtOWFiZDliYTJhZTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA0MTEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0ZmU4OTE0NTBkNzNkYjI0MTViM2VmNzZlNmZlMTE4MTViMWQ3ZWMzNGFiMzUwYzE4NTJmNzNjN2Y2OTViMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.U5vcJQqkt5vx-N6Tu_tzjVvAUjcTF_Z3DKtgjjspFOk) wxfb65081e88b0f684 [**APP**.zip](https://github.com/user-attachments/files/16860864/__APP__.zip)
> > 大部分wxml还是可以解的 看app-wxss.js里面代码是在的 函数好像混淆了
> 
> 图片中错误属正常，不影响解析结果

实际结果确实是少了个比较关键的wxml，但是只处理到app-wxss.js这步的话里面能看到代码 只不过顺序有点乱

**Comment by WolfCanglong** [comment]
> > ![QQ截图20240904123903](https://private-user-images.githubusercontent.com/40590525/364225645-1db4763b-610f-46aa-b810-9abd9ba2ae47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MDU3ODEsIm5iZiI6MTcyNjgwNTQ4MSwicGF0aCI6Ii80MDU5MDUyNS8zNjQyMjU2NDUtMWRiNDc2M2ItNjEwZi00NmFhLWI4MTAtOWFiZDliYTJhZTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA0MTEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0ZmU4OTE0NTBkNzNkYjI0MTViM2VmNzZlNmZlMTE4MTViMWQ3ZWMzNGFiMzUwYzE4NTJmNzNjN2Y2OTViMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.U5vcJQqkt5vx-N6Tu_tzjVvAUjcTF_Z3DKtgjjspFOk) wxfb65081e88b0f684 [**APP**.zip](https://github.com/user-attachments/files/16860864/__APP__.zip)
> > 大部分wxml还是可以解的 看app-wxss.js里面代码是在的 函数好像混淆了
> 
> 图片中错误属正常，不影响解析结果

只解到app-wxss.js时候可以看到里面有一系列
gz$gwx_数字 的函数
但是解到wxml就没有对应的东西

**Comment by Ackites** [comment]
> > > ![QQ截图20240904123903](https://private-user-images.githubusercontent.com/40590525/364225645-1db4763b-610f-46aa-b810-9abd9ba2ae47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MDU3ODEsIm5iZiI6MTcyNjgwNTQ4MSwicGF0aCI6Ii80MDU5MDUyNS8zNjQyMjU2NDUtMWRiNDc2M2ItNjEwZi00NmFhLWI4MTAtOWFiZDliYTJhZTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA0MTEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0ZmU4OTE0NTBkNzNkYjI0MTViM2VmNzZlNmZlMTE4MTViMWQ3ZWMzNGFiMzUwYzE4NTJmNzNjN2Y2OTViMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.U5vcJQqkt5vx-N6Tu_tzjVvAUjcTF_Z3DKtgjjspFOk) wxfb65081e88b0f684 [**APP**.zip](https://github.com/user-attachments/files/16860864/__APP__.zip)
> > > 大部分wxml还是可以解的 看app-wxss.js里面代码是在的 函数好像混淆了
> > 
> > 
> > 图片中错误属正常，不影响解析结果
> 
> 只解到app-wxss.js时候可以看到里面有一系列 gz$gwx_数字 的函数 但是解到wxml就没有对应的东西

gz$gwx 之类的函数还原后就是wxml文件，并不是js代码

**Comment by WolfCanglong** [comment]
> > > > ![QQ截图20240904123903](https://private-user-images.githubusercontent.com/40590525/364225645-1db4763b-610f-46aa-b810-9abd9ba2ae47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MDU3ODEsIm5iZiI6MTcyNjgwNTQ4MSwicGF0aCI6Ii80MDU5MDUyNS8zNjQyMjU2NDUtMWRiNDc2M2ItNjEwZi00NmFhLWI4MTAtOWFiZDliYTJhZTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA0MTEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0ZmU4OTE0NTBkNzNkYjI0MTViM2VmNzZlNmZlMTE4MTViMWQ3ZWMzNGFiMzUwYzE4NTJmNzNjN2Y2OTViMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.U5vcJQqkt5vx-N6Tu_tzjVvAUjcTF_Z3DKtgjjspFOk) wxfb65081e88b0f684 [**APP**.zip](https://github.com/user-attachments/files/16860864/__APP__.zip)
> > > > 大部分wxml还是可以解的 看app-wxss.js里面代码是在的 函数好像混淆了
> > > 
> > > 
> > > 图片中错误属正常，不影响解析结果
> > 
> > 
> > 只解到app-wxss.js时候可以看到里面有一系列 gz$gwx_数字 的函数 但是解到wxml就没有对应的东西
> 
> gz$gwx 之类的函数还原后就是wxml文件，并不是js代码

我的意思就是app-wxss.js存在这些代码的 但是还原到wxml缺失了 说明有一部分代码还原失败了
比如这个小程序里面看app-wxss.js搜“度数”，能看到一些代码，很明显就是html，但是如果选择还原到wxml，生成的里面没有任何一个文件包含“度数”，那个页面的wxml并没有成功还原出来

**Comment by Ackites** [comment]
> > > > > ![QQ截图20240904123903](https://private-user-images.githubusercontent.com/40590525/364225645-1db4763b-610f-46aa-b810-9abd9ba2ae47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MDU3ODEsIm5iZiI6MTcyNjgwNTQ4MSwicGF0aCI6Ii80MDU5MDUyNS8zNjQyMjU2NDUtMWRiNDc2M2ItNjEwZi00NmFhLWI4MTAtOWFiZDliYTJhZTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA0MTEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0ZmU4OTE0NTBkNzNkYjI0MTViM2VmNzZlNmZlMTE4MTViMWQ3ZWMzNGFiMzUwYzE4NTJmNzNjN2Y2OTViMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.U5vcJQqkt5vx-N6Tu_tzjVvAUjcTF_Z3DKtgjjspFOk) wxfb65081e88b0f684 [**APP**.zip](https://github.com/user-attachments/files/16860864/__APP__.zip)
> > > > > 大部分wxml还是可以解的 看app-wxss.js里面代码是在的 函数好像混淆了
> > > > 
> > > > 
> > > > 图片中错误属正常，不影响解析结果
> > > 
> > > 
> > > 只解到app-wxss.js时候可以看到里面有一系列 gz$gwx_数字 的函数 但是解到wxml就没有对应的东西
> > 
> > 
> > gz$gwx 之类的函数还原后就是wxml文件，并不是js代码
> 
> 我的意思就是app-wxss.js存在这些代码的 但是还原到wxml缺失了 说明有一部分代码还原失败了 比如这个小程序里面看app-wxss.js搜“度数”，能看到一些代码，很明显就是html，但是如果选择还原到wxml，生成的里面没有任何一个文件包含“度数”，那个页面的wxml并没有成功还原出来

没有问题，这个包里面没有发现和代码相关的wxml文件名，所以没有还原
