### ISSUE TITLE
小程序版本 11275 不支持了 

### ISSUE THREAD

**Issue by kaka77** [Ackites/KillWxapkg#44]
![image](https://github.com/user-attachments/assets/f9f78c75-34d2-4243-a81d-4f16887f9b2a)

**Comment by yw5820n** [comment]
同问

**Comment by admin8756** [comment]
同求

**Comment by zzhnohikari** [comment]
我的解决方法时把微信回退到上一个版本

**Comment by Ackites** [comment]
> ![image](https://private-user-images.githubusercontent.com/8677125/368842334-f9f78c75-34d2-4243-a81d-4f16887f9b2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MDU5MjEsIm5iZiI6MTcyNjgwNTYyMSwicGF0aCI6Ii84Njc3MTI1LzM2ODg0MjMzNC1mOWY3OGM3NS0zNGQyLTQyNDMtYTgxZC00ZjE2ODg3ZjliMmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjBUMDQxMzQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGQ4NTk4NmI3ZTVjMzJiYzY3ZjM1NGEzNWQ2ZDRjMDViZTFkMjIzNjBkNjcyN2FmYTczNjJkODU1YTg1MzBmOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.BtBLKfeOoE6jNekI988z-UFbfspqsNeowaO5S7wd4lE)

已更新
