### ISSUE TITLE
没有解包结果

### ISSUE THREAD

**Issue by k186** [Ackites/KillWxapkg#50]
你好，我有如下截图的小程序
![image](https://github.com/user-attachments/assets/1f27b585-dbf7-4864-95d7-57599fc06eb6)

### 运行命令
```shell
 .\KillWxapkg_2.4.1_windows_amd64.exe id=<appid>-in="C:\Users\<userName>\Documents\WeChat Files\Applet\<appid>" -out="D:\wxminiunpack\fy"
```
执行后D盘没有结果，并且命令行会提示
![image](https://github.com/user-attachments/assets/b637e6aa-4eac-46f0-82c2-577b6b07ba64)
这是使用方法不对？

### 运行命令
```shell
 .\KillWxapkg_2.4.1_windows_amd64.exe id=<appid>-in="C:\Users\<userName>\Documents\WeChat Files\Applet\<appid>\174\_APP_.wxapkg" -out="D:\wxminiunpack\fy"
```
这样按包解压也没有效果，麻烦指导下，改如何使用~谢谢

## 备注
能运行hook

微信版本：3.9.12.17
RadiumWMPF版本：11275 

![image](https://github.com/user-attachments/assets/0744759f-f8a9-4853-9563-ced71ae1ef9d)

**Comment by xiaotianvm** [comment]
+1 试了很多遍无效

**Comment by Ackites** [comment]
使用有误，麻烦看下文档，检查下输入的命令

**Comment by k186** [comment]
> 使用有误，麻烦看下文档，检查下输入的命令

手动挨个敲就对了。。。复制的 改路径 就不对 - -

**Comment by k186** [comment]
> +1 试了很多遍无效

手动去敲，别复制他文档里面的 直接改。。。
