### ISSUE TITLE
反编译开启美化报错

### ISSUE THREAD

**Issue by kele0722** [Ackites/KillWxapkg#55]
![微信图片_20241029145759](https://github.com/user-attachments/assets/70116aaf-bf26-4e5b-a1f2-b275780ff88c)

**Comment by hgh741** [comment]
请问有解决了吗？

**Comment by Ackites** [comment]
本功能有一定的性能要求，如果解包的文件过大，且电脑配置较低，就会出现这个问题

**Comment by kele0722** [comment]
嗯嗯，对。内存不足
现在有个新问题那个hook不行了，小程序也打不开控制台



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Antkites ***@***.***&gt;
发送时间: 2024年11月11日 17:32
收件人: Ackites/KillWxapkg ***@***.***&gt;
抄送: kele0722 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Ackites/KillWxapkg] 反编译开启美化报错 (Issue #55)





 
本功能有一定的性能要求，如果解包的文件过大，且电脑配置较低，就会出现这个问题
