### ISSUE TITLE
有更详细的命令教程吗

### ISSUE THREAD

**Issue by yixiqiannian** [Ackites/KillWxapkg#6]
跟着文档输命令，一直提示没有该命令

**Comment by Rgwww** [comment]
+1 提示没有program命令

**Comment by Ackites** [comment]
> +1 提示没有program命令

program 是当前程序呀,后面接参数.....

**Comment by Rgwww** [comment]
> 跟着文档输命令，一直提示没有该命令

./KillWxapkg_1.0.0_windows_amd64.exe -id=wx91d27dbf599dff74 -in=输入目录(可以看到.wxapkg后缀文件的那个文件夹路径) -out=结果输出目录
