### ISSUE TITLE
hook报错

### ISSUE THREAD

**Issue by ZXX-9527** [Ackites/KillWxapkg#9]
Error injecting into WeChat PID 9708: the connection is closed
Injected into WeChat instance PID: 9708, Version: 9185
![图片](https://github.com/user-attachments/assets/403c1f75-32be-41d7-98f0-61f7f5beb76a)

**Comment by Ackites** [comment]
> Error injecting into WeChat PID 9708: the connection is closed Injected into WeChat instance PID: 9708, Version: 9185 ![图片](https://private-user-images.githubusercontent.com/52208894/355298422-403c1f75-32be-41d7-98f0-61f7f5beb76a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MTUyODgsIm5iZiI6MTcyMjkxNDk4OCwicGF0aCI6Ii81MjIwODg5NC8zNTUyOTg0MjItNDAzYzFmNzUtMzJiZS00MWQ3LTk4ZjAtNjFmN2Y1YmViNzZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDAzMjk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5YzY1YzBiNDZkZWRjODQwYzEwZTlmOTM1YzU1OWIzM2FjMjNkMTliODM3YzllOTY2NWVkN2Q4YTkwYTY3MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HOA-e0wzPU1K-NxiXeakmpvMtx2Zrn_3gu6jFBRxADA)

可以先打开小程序，注入后再重新加载试试
